In [1]:
import numpy as np

In [15]:
#binomial tree valuation of European call
def bi_tree(K, T, S, sig, r, N):
    #precompute constants
    dt = T/N
    nu = r - 0.5*sig**2
    dxu = np.sqrt(sig**2 * dt + (nu * dt)**2)
    dxd = -dxu
    pu = 1/2 + 1/2 * (nu * dt/dxu)
    pd = 1 - pu
    disc = np.exp(-r*dt)
    
    #initialize asset prices at maturity N
    St = np.empty(N)
    St[0] = S*np.exp(N*dxd)
    for j in range(1,N):
        St[j] = St[j-1] * np.exp(dxu - dxd)
    print(St)
    C = np.empty(N)
    for j in range(N):
        C[j] = max(0.0, St[j] - K)
    print(C)
    #step back through the tree
    for i in range(N-1,0, -1):
        for j in range(i):
            C[j] = disc * (pu*C[j+1] + pd*C[j])
    print(C)
    return C[0]

In [16]:
#test
bi_tree(100, 1, 100, 0.2, 0.06, 3)

[ 70.55963724  89.0263934  112.32623965]
[ 0.          0.         12.32623965]
[ 3.67892529  6.73404149 12.32623965]


3.6789252920175506